### ISSUE TITLE
How to run the time inference only?

### ISSUE THREAD

**Issue by tankle** [hllorens/timeml-qa#2]
can  this project only run the time inference using the timegraph, and then add the inference TLINKs in the end of file?

**Comment by hllorens** [comment]
It could, but why? To make they explicit?
The only related application I see is "remove" inconsistent relations from the annotation.

**Comment by ylmeng** [comment]
Hello hllorens. Back to Semeval 2015 task 5, I saw the QA tool kit for training data (exactly the same as the data set here) contains some systems such as "human-fold1-original", "TIPSem-fold1-original" etc. I suppose they are systems to compare to (baselines), but did not find any explanation. The "human-fold1-timlinks" sees to perform very well, is that from tlinks labeled by humans?
Sorry it is not a question about the code, but I do not know where else to ask.

**Comment by hllorens** [comment]
Yes, you are right: "human" is for "human annotated".
